# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlutterGo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FlutterGo
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'SDWebImage'
  pod 'YYModel'

  target 'FlutterGoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlutterGoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
